[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["cubetastic <cubetastic33@gmail.com>"]
edition = "2018"

[dependencies]
aoc-helper = { version = "0.2.1", features = ["config-file"] }
itertools = "0.8.2"
num = "0.2.0"
tui = "0.7"
termion = "1.5"
